spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: provider
          uri: lb:eureka-consumer
          predicates:
            - Path=/find/**

server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

eureka-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
