eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

remote:
  service:
    url-list:
      - http://localhost:8081/
      - http://localhost:8082/
      - http://localhost:8083/
